# Ceci est un exemple de dockerfile. Il est similaire pour tous les dockers

FROM gcc:latest AS builder
WORKDIR /app
COPY main.c .
RUN gcc -o c2_exec main.c

FROM alpine:latest
RUN apk add --no-cache libc6-compat # Nécessaire pour exécuter du C compilé avec gcc sur Alpine
WORKDIR /root/
COPY --from=builder /app/c2_exec .
CMD ["./c2_exec"]
